# Generated by Django 3.1.7 on 2023-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWorkoutClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=3)),
                ('start_time', models.TimeField(max_length=20)),
                ('end_time', models.TimeField(max_length=20)),
                ('class_pk', models.CharField(max_length=2)),
                ('contents', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('workout', models.CharField(max_length=100)),
                ('set', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=10)),
                ('reps', models.IntegerField(default=10)),
                ('alone_or_group', models.IntegerField(default=0)),
                ('class_pk', models.CharField(default='00', max_length=2)),
                ('completion_rate', models.IntegerField(default=100)),
            ],
        ),
    ]
